import '../.github/scripts/test-environment.mjs';
import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import path from 'node:path';
import os from 'node:os';
import { spawnSync } from 'node:child_process';
import { fileURLToPath } from 'node:url';

const cli = fileURLToPath(new URL('../bin/context-guard-skill.js', import.meta.url));
for (const platform of ['cursor', 'claude']) test(`Installed ${platform} doctor reports an invalid project diagnosis without crashing`, async t => {
  const directory = await fs.mkdtemp(path.join(os.tmpdir(), 'cg-doctor-invalid-'));
  const project = path.join(directory, 'project'), target = path.join(directory, 'installed');
  await fs.mkdir(project);
  const run = (command, args) => spawnSync(command, args, { cwd: project, encoding: 'utf8', timeout: 15000, windowsHide: true });
  for (const args of [['init', '--initial-branch=main'], ['config', 'user.name', 'Synthetic doctor test'], ['config', 'user.email', 'doctor@example.invalid']]) assert.equal(run('git', args).status, 0);
  await fs.writeFile(path.join(project, 'README.md'), 'Synthetic diagnosis fixture\n');
  assert.equal(run('git', ['add', 'README.md']).status, 0);
  assert.equal(run('git', ['commit', '-m', 'fixture']).status, 0);
  const binding = path.join(project, '.git/context-guard/project-binding.json');
  await fs.mkdir(path.dirname(binding), { recursive: true });
  await fs.writeFile(binding, '{}');
  const prior = await fs.readFile(binding, 'utf8');
  assert.equal(run(process.execPath, [cli, 'install', '--platform', platform, '--target', target, '--no-hooks']).status, 0);
  const installed = path.join(target, 'bin/context-guard-skill.js');
  const diagnose = run(process.execPath, [installed, 'workbench', '--diagnose', '--root', project]);
  assert.equal(diagnose.status, 1);
  assert.match(JSON.parse(diagnose.stdout).error.message, /Invalid project binding/);
  const doctor = run(process.execPath, [installed, 'doctor', '--platform', platform, '--target', target, '--root', project, '--json']);
  assert.equal(doctor.status, 1, 'missing project files/hooks remain not ready');
  const report = JSON.parse(doctor.stdout);
  assert.equal(report.ok, false);
  const workbench = report.results.find(result => result.name === 'project.workbench');
  assert.equal(workbench.ok, false); assert.equal(workbench.required, false);
  assert.equal(JSON.parse(workbench.detail).status, 'unknown');
  assert.equal(await fs.readFile(binding, 'utf8'), prior, 'doctor cannot repair or replace an invalid binding');
  assert.doesNotMatch(doctor.stderr, /TypeError|Cannot read properties/);
  t.diagnostic('Synthetic failure and installed-entry evidence retained: ' + directory);
});
